# =========================================================================
# CONFIGURACIÓN PARA DESARROLLO LOCAL (IntelliJ)
# =========================================================================
server:
  port: 8080

spring:
  application:
    name: Millete
  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/millete_db
    username: postgres
    password: 654321
    driver-class-name: org.postgresql.Driver

  mail:
    host: localhost
    port: 25
    username:
    password:
    from: noreply@millete.online
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  version: 0.0.2
  frontend:
    url: http://localhost:3000

jwt:
  secret: U3VwZXJTZWNy5XRfSldUX0tleV9Gb3JfVGVzdGluZ187MDI2X01pbGxldGUK
  expiration: 43200000

logging:
  level:
    root: INFO
    com.puntomartinez: DEBUG